using System;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;
using API.Infrastructure.Helpers;
using MailKit.Net.Smtp;
using Microsoft.Extensions.Options;
using MimeKit;
using ZXing.QrCode;

namespace API.Features.Reservations {

    public class ReservationSendToEmail : IReservationSendToEmail {

        private readonly EmailSettings emailSettings;

        public ReservationSendToEmail(IOptions<EmailSettings> emailSettings) {
            this.emailSettings = emailSettings.Value;
        }

        public async Task SendReservationToEmail(BoardingPassReservationVM reservation) {
            string FilePath = Directory.GetCurrentDirectory() + "\\Features\\Reservations\\Templates\\BoardingPasss.cshtml";
            StreamReader str = new(FilePath);
            string MailText = str.ReadToEnd();
            str.Close();
            MailText = MailText
                .Replace("[logo]", SetLogoAsBackground())
                .Replace("[date]", DateHelpers.FormatDateStringToLocaleString(reservation.Date))
                .Replace("[destination]", reservation.Destination.Description)
                .Replace("[refNo]", reservation.RefNo)
                .Replace("[phones]", emailSettings.Phones)
                .Replace("[pickupPoint]", reservation.PickupPoint.Description)
                .Replace("[exactPoint]", reservation.PickupPoint.ExactPoint)
                .Replace("[time]", reservation.PickupPoint.Time)
                .Replace("[image]", SetBarcodeAsBackground(reservation.RefNo));
            var senderEmail = new MimeMessage {
                Sender = MailboxAddress.Parse(emailSettings.UserName)
            };
            senderEmail.From.Add(new MailboxAddress(emailSettings.From, emailSettings.UserName));
            senderEmail.To.Add(MailboxAddress.Parse(reservation.Email));
            senderEmail.Subject = "Your reservation is ready!";
            var builder = new BodyBuilder {
                HtmlBody = MailText
            };
            senderEmail.Body = builder.ToMessageBody();
            using var smtp = new SmtpClient();
            smtp.Connect(emailSettings.SmtpClient, emailSettings.Port);
            smtp.Authenticate(emailSettings.UserName, emailSettings.Password);
            await smtp.SendAsync(senderEmail);
            smtp.Disconnect(true);
        }

        private static string SetBarcodeAsBackground(string refNo) {
            return "background: url(data:image/png;base64," + Convert.ToBase64String(CreateBarcode(refNo, 250, 250, 2)) + ")";
        }

        private static string SetLogoAsBackground() {
            return "background: url(data:image/png;base64," + GetBase64Logo() + ")";
        }

        private static byte[] CreateBarcode(string text, int width, int height, int margin) {
            byte[] byteArray;
            var qrCodeWriter = new ZXing.BarcodeWriterPixelData {
                Format = ZXing.BarcodeFormat.QR_CODE,
                Options = new QrCodeEncodingOptions {
                    Height = height,
                    Width = width,
                    Margin = margin
                }
            };
            var pixelData = qrCodeWriter.Write(text);
            using (var bitmap = new Bitmap(pixelData.Width, pixelData.Height, System.Drawing.Imaging.PixelFormat.Format32bppRgb)) {
                using var ms = new MemoryStream();
                var bitmapData = bitmap.LockBits(new Rectangle(0, 0, pixelData.Width, pixelData.Height), System.Drawing.Imaging.ImageLockMode.WriteOnly, System.Drawing.Imaging.PixelFormat.Format32bppRgb);
                try {
                    System.Runtime.InteropServices.Marshal.Copy(pixelData.Pixels, 0, bitmapData.Scan0, pixelData.Pixels.Length);
                } finally {
                    bitmap.UnlockBits(bitmapData);
                }
                bitmap.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                byteArray = ms.ToArray();
            }
            return byteArray;
        }

        private static string GetBase64Logo() {
            return "iVBORw0KGgoAAAANSUhEUgAAAxoAAARjCAYAAADoylLVAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAH5VJREFUeJzt3XvQ7XtB1/HP4SKEiHEOagpYYwlWRtPYUIRmNtMfgN1EsstgoQNWZkl0sYtFNNHFKC9J2RjTpE3liJPJJF1GI+scBU0TkEQpy0sKIhfBg3LZ/fF7ntmLh+ew2Xu/z9lIr9fMM2s/67fWb33Xb/+z3s/3912/265cubJtH73tedt+57aP2fZ/tv2LbX992zv2i9uv2fE+ftu2h2577bav3vY1267cumEBAMCHrtuuXLlyx7bv2vYrt71s2yu3PW7bb93277Y9edt7btkIb86v3/Yd2x6y7Vu2/d9tn7rt123729u+5NYNDQAAPnTdduXKlb+/7Yu3/YVtf+tk2/O2fem2p277plswtsLLtn3atiftiKZte8C2b9z2mdses+1/3pqhAQDAh67brly58rptD9728dvefbLtodvesu1F2555C8Z2sx6+7Y3bXrpjVubUE7f9l21fuO2F9/G4AADgQ94Dtj1623/ee0fGtr1tx6lGj7rkeY/c9tu33X/bt+1Y03HqE7f98pPff2zbD13yGo/f9rBL9v+abT++7RPOfl6+7a0n2z9j25u2fd8lzz33qG23bXvVJdt++OR9nHvsjmNx7kfPxnzxtLEnnO33zpP7PmrHaVqv2vaTZ/f92m0fu+P4nO7j0TtO33rbjlPWXn9h/xeP3bl37pihOfdh2z59x5qaV2/73kueAwAAt8QDtj1w29vvYfvdZ9tPfe62f7ztQWe/v3Pbs3cssD73Bduec+F5r972R7Z998l9X7UjNi565rav3fb0bc/d9hu3fc/J9pds+/Ydpz/dk/Nx/9wl2+6+8JjtmN34oguP+/6zMZ9+iH/RtvvtCJNzT9j2zWfj/fqz+/7cjmP1kJPX+7xt/+jkde/e9lk7Zl3OPWvbn7lkzD+9I2i2Iy6+fduvPtn+Tds+exa4AwDwQeAB19h++hf67Zgl+Ic7vrnp83d8iP+abV+xY1bklRee/6xt/2vHWojnb/vXO/5if/fJY9624xuhTv3vD/QN3KB37wiXH79k2zN2zMB80q6O+THbfv4mX/MR2758x/F85rZf2PZPdoTHYy/Z/1P33sfhXSf//is7IuP52168I4a+aNvnbPuXNzlOAAC4adcKjd974ffP2vEX+j+/7RVn9z17x6lNn7n3DY3vPLvvP+6YAfl7O073Of0L/vmH/vvS23fMklzmrm0/uGPMH75jgfwTd5wCdTM+bdtHbPuLu7ow/QXb/sGO06z+24XHv/psHJd5yrbXbfvLO2YwXr0jkJ40oQEAwAeB+13n43/F2e3pB+DXnN1+4jWee76e4uOu8zVvpXLM52tdfuTkvvN/P3rX51E7ZjvOT5P6+W0/cQP7AQCAe8X1hsb9z25PFze/+8K2e3J+6s+1HvfBpBzzZcfu/N838v9wcWH9e25gPwAAcK+41qlT3LvesuO0sTcH+3r1tp8J9gMAADdNaNx3zk9zOj3md+6e14pca18Xvw3ss29kUAAAcG9wqs1957Vnt39ox3U4bsYP7fha4GutiwEAgFtCaNx3XrrtG7b9vh3fOnUzC7e/YMfMyHdu+4M3PzQAAGjdl6Hx0LPbe7o44Aej8zFfdtG/63Vlx2zG39lxVfVXbvvju7HZjf+049ojP7vtn++4WOBlV3AHAIBb4r4Mjd91dvua9/uoDy7nY/6BaH/v2nENkt+840KGX73jKucfdgP7umvH9Tf+7o7ravz3HdfqAACAW+5ai8H/7Y7rNfyxG9z/5+24Evbjtv2BHacMfd+Fxzx4x0Xxzr1224tu8PU+ULdv+/fbvm7HVc1PPXPbG7b9hh1X2n7Jjm90Kn33tt+0430/e9tf2vZXLzzmObv6LVLv3Pall+zn7dv+7I6rl794x6lZv2q/uGaNAAD4EHSt0Hjcbuyv7ee++MLv79rxbUm/cHLfg3b8lf/cS3fvh8YDt33KLr/a93Mu/P6uHcfpXZc89nr80W3P3/a7t33HjmPwp7c9bdvv2PuGxufs6rUy7t57h8bP7DhO5+sz/uu2L9sxu/HJ277rJscKAAA35X7b3rHtYfew/aE71gHcqE/dMXvw0TtmDp6y4wP0qbfsWKdw/vOkk21XduPecXb7EZdsO197cdl7e/yOMX/Mthdu+z3bnnoT4zj3oG0P3/t+Le1bL7nvdBy3b3vkhW0P39X3cO78vVy2LwAAuE/db8epSo/b9uEXtj1220fu6teybtvrz27vOLnvjgvbTr1125t2nIr0T8/ue8x1jO+nzm5vP7nvwdt+yT283qkf2TFr8IRLtj3+7Pa1l2w7H/Prd3XMjz3Z/pMXxrNtv/Ts9v2N6Q1ntxcD4Y5tP/1+nneZn7pkP+djut59AQBA7n47Pkzfvu0F2+5/dv8Dt/3NHTMKLz55/F1nt1+4q9+W9Myz2zuv8VrnpwFdzwL0u87G8Lkn9z3t7LWv9Xo/t2PNwhP23mtMHr5jTcTP7lin8f5cNuY7tz1ix+zM+ban7ZhB+d73s6/v2faebU8/2d9TdsycvOIa47joFdt+y65eR+Mh237/tjdue9117gsAAHIP2PZV256849oMT972P3ac5/+xO877f/nJ479t27/Z9oxtn77jw/wn7/jw/c33wvi+f0cIPWPHrMubtj1xx+Lsf/YBPP85O77h6YXb/sSO2YhP2XE61dPP9ne9XrDtD+8IsDt3HKdP2va8XZ21uMwP7jjWf2rbq87G8sSz51xckL4dx/3dJ7+/cVfD4ku2fcaOReUv3zHj8uhtf3LHwnEAALil7v/c5z73Pdv+1Y4Fxr/s7Oe1Oz7MfuUlz/nGHd9q9HE7PtR+3Y4Zg3ecPOZh2968Y8Hy6dqBh2572Y6Y2baP2vbDZ4+7J99ytq9PONvHN2z7/G1v+wDe39u3ff2OmYRH7jhN6a5tz9r2rRce+5E7jsG37uq3Nj1wxyllL9vV06zuPtvnHds+fsfpUn9j25df2N/Dd5zi9JKz19+Ob9360R2zGLdv+w87ouUnLozjzTti5AdOfl65qzMwbzg7Do84e18/tu2vbfvaax8SAAC499125crNrLcGAAB4X/flBfsAAID/TwgNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAICc0AAAAHJCAwAAyAkNAAAgJzQAAIDc/wNnA5qYa7/odAAAAABJRU5ErkJggg==";
        }

    }

}
